[tox]
envlist =
    email-profile-py38
    email-profile-py39
    email-profile-py310
    email-profile-py311
    email-profile-py312
    email-profile-py313
    email-profile-py314

[email-profile-py38]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.8
commands =
    pytest

[email-profile-py39]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.9
commands =
    pytest

[email-profile-py310]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.10
commands =
    pytest

[email-profile-py311]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.11
commands =
    pytest

[email-profile-py312]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.12
commands =
    pytest

[email-profile-py313]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.13
commands =
    pytest

[email-profile-py314]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/email-profile
basepython = python3.14
commands =
    pytest
